sudo: false
language: python
env:
  matrix:
  - STEP=1-hello-world
  - STEP=2-structured-data
  - STEP=3-binary-data
  - STEP=4-auth
  - STEP=5-logging
  - STEP=6-pubsub
  - STEP=7-gce
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client-secret.json
before_install:
- openssl aes-256-cbc -K $encrypted_82d8befc5c58_key -iv $encrypted_82d8befc5c58_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar -xzf secrets.tar.gz
- pip install tox
before_script:
- echo $GOOGLE_APPLICATION_CREDENTIALS
- ls $TRAVIS_BUILD_DIR
- cp config.py $TRAVIS_BUILD_DIR/$STEP
- cd $TRAVIS_BUILD_DIR/$STEP
script:
- tox
